name: W65C816S
version: 0.1.0

default-extensions:
  - ApplicativeDo

library:
  source-dirs: lib
  dependencies:
    - base
    - optics
    - binary
    - bytestring
    - transformers

executable:
  source-dirs: exe
  main: Test
  dependencies:
    - base